# Use the official MongoDB image as the base image
FROM mongo:latest

# Optionally, set environment variables for MongoDB configuration
ENV MONGO_INITDB_ROOT_USERNAME=Artorise
ENV MONGO_INITDB_ROOT_PASSWORD=7Rb$e9@1

# Expose the default MongoDB port (27017)
EXPOSE 27017
# Start the MongoDB server when the container starts
CMD ["mongod"]
